[project]
name = "terraform-templates"
version = "0.1.0"
description = "A collection of Terraform modules and templates for provisioning cloud resources"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
]
